-- @migrate/up
CREATE TABLE IF NOT EXISTS user(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	Created TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	Modified TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

	Name VARCHAR(70) NOT NULL,
	Email VARCHAR(255) NOT NULL UNIQUE KEY,
	Password VARCHAR(255) NOT NULL
);

-- @migrate/down
DROP TABLE IF EXISTS user;
